# Generated by Django 3.2 on 2024-05-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
