# Generated by Django 3.2 on 2024-05-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240506_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
