# Generated by Django 3.2 on 2024-05-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shoppingcart_unique_key_user_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
