# Generated by Django 3.2 on 2024-05-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240526_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'default_related_name': 'ingredient_recipe', 'verbose_name': 'ингредиенты рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'default_related_name': 'tag_recipe', 'verbose_name': 'тэги рецепта', 'verbose_name_plural': 'Тэги рецептов'},
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_key_user_recipe',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='recipes.recipe', verbose_name='Рецепт в избранном'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_key_user_recipe_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_key_user_recipe_shopcart'),
        ),
    ]
